
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

#整合mybatis
mybatis:
  type-aliases-package: com.example.demo5.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml

  config-location: classpath:mybatis/mybatis_config.xml


hello:
  prefix: ccccccc
  suffix: jcccccc