

spring:
  datasource:
    #    驱动
    url: jdbc:mysql://localhost:3306/yuangong?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo3.pojo


